// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: cluster_messages.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a request to join a cluster.
type JoinCluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port     string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *JoinCluster) Reset() {
	*x = JoinCluster{}
	mi := &file_cluster_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCluster) ProtoMessage() {}

func (x *JoinCluster) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCluster.ProtoReflect.Descriptor instead.
func (*JoinCluster) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{0}
}

func (x *JoinCluster) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *JoinCluster) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

// Represents a request to leave a cluster.
type LeaveCluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port     string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *LeaveCluster) Reset() {
	*x = LeaveCluster{}
	mi := &file_cluster_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCluster) ProtoMessage() {}

func (x *LeaveCluster) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCluster.ProtoReflect.Descriptor instead.
func (*LeaveCluster) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{1}
}

func (x *LeaveCluster) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *LeaveCluster) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

// Represents gossip containing a disowned entry.
type Gossip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disowned *DisownedEntry `protobuf:"bytes,1,opt,name=disowned,proto3" json:"disowned,omitempty"`
}

func (x *Gossip) Reset() {
	*x = Gossip{}
	mi := &file_cluster_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gossip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gossip) ProtoMessage() {}

func (x *Gossip) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gossip.ProtoReflect.Descriptor instead.
func (*Gossip) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Gossip) GetDisowned() *DisownedEntry {
	if x != nil {
		return x.Disowned
	}
	return nil
}

// Represents a gossip message for batch and a disowned entry.
type GossipBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disowned *DisownedEntry `protobuf:"bytes,1,opt,name=disowned,proto3" json:"disowned,omitempty"`
}

func (x *GossipBatch) Reset() {
	*x = GossipBatch{}
	mi := &file_cluster_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipBatch) ProtoMessage() {}

func (x *GossipBatch) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipBatch.ProtoReflect.Descriptor instead.
func (*GossipBatch) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GossipBatch) GetDisowned() *DisownedEntry {
	if x != nil {
		return x.Disowned
	}
	return nil
}

// Represents a suspect check.
type SuspectCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SuspectCheck) Reset() {
	*x = SuspectCheck{}
	mi := &file_cluster_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspectCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectCheck) ProtoMessage() {}

func (x *SuspectCheck) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectCheck.ProtoReflect.Descriptor instead.
func (*SuspectCheck) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{4}
}

// Represents an entry that has been disowned.
type DisownedEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target    string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	SeenCount int32  `protobuf:"varint,2,opt,name=seenCount,proto3" json:"seenCount,omitempty"`
}

func (x *DisownedEntry) Reset() {
	*x = DisownedEntry{}
	mi := &file_cluster_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisownedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisownedEntry) ProtoMessage() {}

func (x *DisownedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisownedEntry.ProtoReflect.Descriptor instead.
func (*DisownedEntry) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DisownedEntry) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DisownedEntry) GetSeenCount() int32 {
	if x != nil {
		return x.SeenCount
	}
	return 0
}

// Represents a SWIM Ping message.
type SwimPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   string         `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target   string         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Disowned *DisownedEntry `protobuf:"bytes,3,opt,name=disowned,proto3" json:"disowned,omitempty"`
}

func (x *SwimPing) Reset() {
	*x = SwimPing{}
	mi := &file_cluster_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwimPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimPing) ProtoMessage() {}

func (x *SwimPing) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimPing.ProtoReflect.Descriptor instead.
func (*SwimPing) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SwimPing) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SwimPing) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SwimPing) GetDisowned() *DisownedEntry {
	if x != nil {
		return x.Disowned
	}
	return nil
}

// Represents a SWIM Acknowledgment (ACK) message.
type SwimAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *SwimAck) Reset() {
	*x = SwimAck{}
	mi := &file_cluster_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwimAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimAck) ProtoMessage() {}

func (x *SwimAck) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimAck.ProtoReflect.Descriptor instead.
func (*SwimAck) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SwimAck) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SwimAck) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// Represents a SWIM Ping Request message.
type SwimPingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   string         `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target   string         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Disowned *DisownedEntry `protobuf:"bytes,3,opt,name=disowned,proto3" json:"disowned,omitempty"`
}

func (x *SwimPingReq) Reset() {
	*x = SwimPingReq{}
	mi := &file_cluster_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwimPingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimPingReq) ProtoMessage() {}

func (x *SwimPingReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimPingReq.ProtoReflect.Descriptor instead.
func (*SwimPingReq) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SwimPingReq) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SwimPingReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SwimPingReq) GetDisowned() *DisownedEntry {
	if x != nil {
		return x.Disowned
	}
	return nil
}

// Represents a SWIM ACK Request message.
type SwimAckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *SwimAckReq) Reset() {
	*x = SwimAckReq{}
	mi := &file_cluster_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwimAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimAckReq) ProtoMessage() {}

func (x *SwimAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimAckReq.ProtoReflect.Descriptor instead.
func (*SwimAckReq) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SwimAckReq) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SwimAckReq) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_cluster_messages_proto protoreflect.FileDescriptor

var file_cluster_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x3d, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x3e, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x3c, 0x0a, 0x06, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x22, 0x41,
	0x0a, 0x0b, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x32, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x73, 0x6f, 0x77, 0x6e,
	0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65,
	0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x22, 0x45, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x65, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73,
	0x65, 0x65, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x6e, 0x0a, 0x08, 0x53, 0x77, 0x69, 0x6d,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x44, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x64, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x22, 0x39, 0x0a, 0x07, 0x53, 0x77, 0x69, 0x6d,
	0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x71, 0x0a, 0x0b, 0x53, 0x77, 0x69, 0x6d, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44,
	0x69, 0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x6f, 0x77, 0x6e, 0x65, 0x64, 0x22, 0x3c, 0x0a, 0x0a, 0x53, 0x77, 0x69, 0x6d, 0x41, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x42, 0x18, 0x5a, 0x16, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cluster_messages_proto_rawDescOnce sync.Once
	file_cluster_messages_proto_rawDescData = file_cluster_messages_proto_rawDesc
)

func file_cluster_messages_proto_rawDescGZIP() []byte {
	file_cluster_messages_proto_rawDescOnce.Do(func() {
		file_cluster_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cluster_messages_proto_rawDescData)
	})
	return file_cluster_messages_proto_rawDescData
}

var file_cluster_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cluster_messages_proto_goTypes = []any{
	(*JoinCluster)(nil),   // 0: cluster.JoinCluster
	(*LeaveCluster)(nil),  // 1: cluster.LeaveCluster
	(*Gossip)(nil),        // 2: cluster.Gossip
	(*GossipBatch)(nil),   // 3: cluster.GossipBatch
	(*SuspectCheck)(nil),  // 4: cluster.SuspectCheck
	(*DisownedEntry)(nil), // 5: cluster.DisownedEntry
	(*SwimPing)(nil),      // 6: cluster.SwimPing
	(*SwimAck)(nil),       // 7: cluster.SwimAck
	(*SwimPingReq)(nil),   // 8: cluster.SwimPingReq
	(*SwimAckReq)(nil),    // 9: cluster.SwimAckReq
}
var file_cluster_messages_proto_depIdxs = []int32{
	5, // 0: cluster.Gossip.disowned:type_name -> cluster.DisownedEntry
	5, // 1: cluster.GossipBatch.disowned:type_name -> cluster.DisownedEntry
	5, // 2: cluster.SwimPing.disowned:type_name -> cluster.DisownedEntry
	5, // 3: cluster.SwimPingReq.disowned:type_name -> cluster.DisownedEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cluster_messages_proto_init() }
func file_cluster_messages_proto_init() {
	if File_cluster_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cluster_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_messages_proto_goTypes,
		DependencyIndexes: file_cluster_messages_proto_depIdxs,
		MessageInfos:      file_cluster_messages_proto_msgTypes,
	}.Build()
	File_cluster_messages_proto = out.File
	file_cluster_messages_proto_rawDesc = nil
	file_cluster_messages_proto_goTypes = nil
	file_cluster_messages_proto_depIdxs = nil
}
